#!/usr/bin/with-contenv sh

UID=${UID:-911}
GID=${GID:-911}

#if [ -z "`getent group $GID`" ]; then
#    addgroup -S -g $GID users
#else
#    groupmod -n users `getent group $GID | cut -d: -f1`
#fi

#if [ -z "`getent passwd $UID`" ]; then
#   adduser -S -u $UID -G users -s /bin/sh user
#else
#    usermod -l user -g $GID -d /srv -m `getent passwd $UID | cut -d: -f1`
#fi

#echo "user ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/user
#chmod 0440 /etc/sudoers.d/user


