#!/usr/bin/with-contenv bash

PUID=${PUID:-911}
PGID=${PGID:-911}

groupmod -o -g "$PGID" trojancaddy
usermod -o -u "$PUID" trojancaddy

chown trojancaddy:trojancaddy /srv
chown trojancaddy:trojancaddy /config
chown trojancaddy:trojancaddy /defaults
