#!/usr/bin/with-contenv sh

echo 'INIT...'

[[ ! -f /config/caddy/config.json ]] && \
  cp /defaults/caddy.json /config/caddy/config.json

[[ ! -f /srv/caddy/index.html ]] && \
  cp /defaults/index.html /srv/caddy/index.html

[[ ! -f /config/trojan/config.json ]] && \
  cp /defaults/trojan.json /config/trojan/config.json
